name: CI

on:
  push: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        target_cpus:
          - "@local_config_platform//:host"
          - "@bazel_embedded//platforms:cortex_m0"
          - "@bazel_embedded//platforms:cortex_m3"
          - "@bazel_embedded//platforms:cortex_m4"
          - "@bazel_embedded//platforms:cortex_m4_fpu"
          - "@bazel_embedded//platforms:cortex_m7"
          - "@bazel_embedded//platforms:cortex_m7_fpu"
        example_dirs:
          - examples/minimal_stm32l4_cubemx
          - examples/arm_none_eabi_simple
          - examples/minimal_mbedtls
          - examples/minimal_stm32h7_cubemx
    steps:
      - uses: actions/checkout@v1

      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.3.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Test
        run: |
          cd ${{ matrix.example_dirs }} ||
          "${GITHUB_WORKSPACE}/bin/bazel" test //...

      - name: Build
        run: |
          cd ${{ matrix.example_dirs }} ||
          "${GITHUB_WORKSPACE}/bin/bazel" build //... --platforms=${{ matrix.target_cpus }}
