name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        uri:
          - os: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: ${{ runner.os }}-bazel

      - name: Install bazelisk For linux
        if: ${{ matrix.os == 'ubuntu-18.04' }}
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.3.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
      - name: Install bazelisk For Mac osx
        if: ${{ matrix.os == 'macos-10.15' }}
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.6.1/bazelisk-darwin-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-darwin-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Test
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" test //...

      - name: Build
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" build  --platforms=@local_config_platform//:host -- //... -//tools/...
          "${GITHUB_WORKSPACE}/bin/bazel" build  --platforms=@bazel_embedded//platforms:cortex_m0 -- //... -//tools/...
          "${GITHUB_WORKSPACE}/bin/bazel" build  --platforms=@bazel_embedded//platforms:cortex_m3 -- //... -//tools/...
          "${GITHUB_WORKSPACE}/bin/bazel" build  --platforms=@bazel_embedded//platforms:cortex_m4 -- //... -//tools/...
          "${GITHUB_WORKSPACE}/bin/bazel" build  --platforms=@bazel_embedded//platforms:cortex_m4_fpu -- //... -//tools/...
          "${GITHUB_WORKSPACE}/bin/bazel" build  --platforms=@bazel_embedded//platforms:cortex_m7 -- //... -//tools/...
          "${GITHUB_WORKSPACE}/bin/bazel" build  --platforms=@bazel_embedded//platforms:cortex_m7_fpu -- //... -//tools/...
